In [1]:
# 查看当前kernel下已安装的包  list packages
!pip list --format=columns

Package                   Version
------------------------- -----------
absl-py                   0.11.0
aliyun-python-sdk-core    2.13.5
aliyun-python-sdk-core-v3 2.13.3
aliyun-python-sdk-kms     2.7.1
argon2-cffi               20.1.0
asn1crypto                0.23.0
astor                     0.8.0
astunparse                1.6.3
async-generator           1.10
attrs                     20.3.0
backcall                  0.2.0
bleach                    3.2.1
cachetools                4.2.1
certifi                   2020.12.5
cffi                      1.14.4
chardet                   4.0.0
cloudpickle               1.6.0
conda                     4.9.2
conda-package-handling    1.3.11
crcmod                    1.7
cryptography              2.3.1
cycler                    0.10.0
Cython                    0.29.21
dataclasses               0.8
decorator                 4.4.2
defusedxml                0.6.0
dlib                      19.21.1
dsw-demos-extension       0.1.0
dsw-ipykernel             0.2.0
dsw-magic                 0.0.1
dsw-sql-extension         0.1.0
dswdlv                    0.0.1
dswmagic                  0.0.1
entrypoints               0.3
faiss                     1.4.0
fasttext                  0.9.2
ffmpeg-python             0.2.0
flatbuffers               1.12
future                    0.17.1
gast                      0.3.3
google-auth               1.27.1
google-auth-oauthlib      0.4.3
google-pasta              0.2.0
graphviz                  0.16
grpcio                    1.32.0
h5py                      2.10.0
idna                      2.10
imbalanced-learn          0.3.1
importlib-metadata        3.3.0
ipykernel                 5.4.2
ipython                   7.9.0
ipython-genutils          0.2.0
jedi                      0.17.2
Jinja2                    2.11.2
jmespath                  0.9.4
joblib                    1.0.0
json5                     0.9.5
jsonschema                3.2.0
jupyter-client            6.1.7
jupyter-core              4.7.0
jupyterlab                2.2.8
jupyterlab-launcher       0.13.1
jupyterlab-prometheus     0.1
jupyterlab-pygments       0.1.2
jupyterlab-server         1.2.0
Keras                     2.2.4
Keras-Applications        1.0.8
Keras-Preprocessing       1.1.2
kiwisolver                1.2.0
libarchive-c              2.8
lightgbm                  2.3.1
Markdown                  3.1.1
MarkupSafe                1.1.1
matplotlib                3.3.3
mistune                   0.8.4
mkl-fft                   1.0.4
mkl-random                1.0.1
nbclient                  0.5.1
nbconvert                 6.0.7
nbformat                  5.0.8
nest-asyncio              1.4.3
notebook                  6.1.6
np-utils                  0.5.10.0
numpy                     1.19.4
oauthlib                  3.1.0
odps                      3.5.1
olefile                   0.46
open-from-url             0.1.0
opt-einsum                3.3.0
oss2                      2.8.0
packaging                 20.8
palettable                3.3.0
pandas                    1.1.5
pandocfilters             1.4.3
parso                     0.7.1
pexpect                   4.8.0
pickleshare               0.7.5
Pillow                    8.0.1
pip                       21.0.1
prometheus-client         0.9.0
prompt-toolkit            2.0.10
protobuf                  3.15.5
ptyprocess                0.7.0
pyasn1                    0.4.8
pyasn1-modules            0.2.8
pybind11                  2.6.1
pycosat                   0.6.3
pycparser                 2.20
pycryptodome              3.8.2
Pygments                  2.7.3
pymars                    0.6.1
pyodps                    0.10.3
pyOpenSSL                 17.5.0
pyparsing                 2.4.7
pyrsistent                0.17.3
PySocks                   1.6.7
python-dateutil           2.8.1
python-dotenv             0.15.0
pytz                      2020.5
PyYAML                    5.1.2
pyzmq                     20.0.0
requests                  2.25.1
requests-oauthlib         1.3.0
rsa                       4.7.2
ruamel-yaml               0.11.14
scikit-learn              0.24.0
scipy                     1.5.4
seaborn                   0.10.1
Send2Trash                1.5.0
setuptools                51.1.1
six                       1.15.0
sklearn                   0.0
sqlflow                   0.15.0.dev0
tensorboard               2.4.1
tensorboard-plugin-wit    1.8.0
tensorflow                1.14.0
tensorflow-cpu            2.4.0
tensorflow-estimator      2.4.0
tensorflow-io             0.7.0
termcolor                 1.1.0
terminado                 0.9.1
testpath                  0.4.4
threadpoolctl             2.1.0
tianchi-extension         0.1.0
torch                     1.7.1
torchvision               0.3.0
tornado                   6.1
tqdm                      4.32.1
traitlets                 4.3.3
typing-extensions         3.7.4.3
urllib3                   1.26.2
wcwidth                   0.2.5
webencodings              0.5.1
Werkzeug                  0.15.5
wheel                     0.36.2
wrapt                     1.12.1
xgboost                   0.90
zipp                      3.4.0
WARNING: You are using pip version 21.0.1; however, version 21.3.1 is available.
You should consider upgrading via the '/opt/conda/bin/python -m pip install --upgrade pip' command.

In [3]:
# 安装拓展包
!pip install some_package --user

Looking in indexes: https://mirrors.cloud.aliyuncs.com/pypi/simple/
Requirement already satisfied: some_package in /root/.local/lib/python3.6/site-packages (0.1)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [4]:
# 举例：安装sklearn某依赖库
!pip install sklearn2pmml --user

Looking in indexes: https://mirrors.cloud.aliyuncs.com/pypi/simple/
Requirement already satisfied: sklearn2pmml in /root/.local/lib/python3.6/site-packages (0.87.1)
Requirement already satisfied: joblib>=0.13.0 in /home/pai/lib/python3.6/site-packages (from sklearn2pmml) (1.1.0)
Requirement already satisfied: scikit-learn>=0.18.0 in /home/pai/lib/python3.6/site-packages (from sklearn2pmml) (0.24.2)
Requirement already satisfied: sklearn-pandas>=0.0.10 in /root/.local/lib/python3.6/site-packages (from sklearn2pmml) (2.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/pai/lib/python3.6/site-packages (from scikit-learn>=0.18.0->sklearn2pmml) (3.1.0)
Requirement already satisfied: numpy>=1.13.3 in /root/.local/lib/python3.6/site-packages (from scikit-learn>=0.18.0->sklearn2pmml) (1.19.5)
Requirement already satisfied: scipy>=0.19.1 in /root/.local/lib/python3.6/site-packages (from scikit-learn>=0.18.0->sklearn2pmml) (1.5.4)
Requirement already satisfied: pandas>=1.1.4 in /root/.local/lib/python3.6/site-packages (from sklearn-pandas>=0.0.10->sklearn2pmml) (1.1.5)
Requirement already satisfied: pytz>=2017.2 in /home/pai/lib/python3.6/site-packages (from pandas>=1.1.4->sklearn-pandas>=0.0.10->sklearn2pmml) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /home/pai/lib/python3.6/site-packages (from pandas>=1.1.4->sklearn-pandas>=0.0.10->sklearn2pmml) (2.8.0)
Requirement already satisfied: six>=1.5 in /home/pai/lib/python3.6/site-packages (from python-dateutil>=2.7.3->pandas>=1.1.4->sklearn-pandas>=0.0.10->sklearn2pmml) (1.16.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

In [2]:
import pandas as pd

In [16]:
dataset = pd.read_csv('car_price.csv')

In [17]:
dataset_copy = dataset.copy()

In [18]:
dataset_copy

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [19]:
dataset_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   car_ID            205 non-null    int64
 1   symboling         205 non-null    int64
 2   CarName           205 non-null    object
 3   fueltype          205 non-null    object
 4   aspiration        205 non-null    object
 5   doornumber        205 non-null    object
 6   carbody           205 non-null    object
 7   drivewheel        205 non-null    object
 8   enginelocation    205 non-null    object
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64
 14  enginetype        205 non-null    object
 15  cylindernumber    205 non-null    object
 16  enginesize        205 non-null    int64
 17  fuelsystem        205 non-null    object
 18  boreratio         205 non-null    float64
 19  stroke            205 non-null    float64
 20  compressionratio  205 non-null    float64
 21  horsepower        205 non-null    int64
 22  peakrpm           205 non-null    int64
 23  citympg           205 non-null    int64
 24  highwaympg        205 non-null    int64
 25  price             205 non-null    float64
dtypes: float64(8), int64(8), object(10)
memory usage: 41.8+ KB

In [49]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
columns_to_convert = list(dataset_copy.select_dtypes(include='object').columns)
columns_to_convert.remove('CarName')
for i in columns_to_convert:
    dataset_copy[i + 'copy']= le.fit_transform(dataset_copy[i])
dataset_copy_new = dataset_copy.drop(columns_to_convert,axis=1)
dataset_copy_new = dataset_copy_new.drop(columns ='CarNamecopy')

In [52]:
dataset_copy_new

,car_ID,symboling,CarName,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,...,price,fueltypecopy,aspirationcopy,doornumbercopy,carbodycopy,drivewheelcopy,enginelocationcopy,enginetypecopy,cylindernumbercopy,fuelsystemcopy
0,1,3,alfa-romero giulia,88.6,168.8,64.1,48.8,2548,130,3.47,...,13495.0,1,0,1,0,2,0,0,2,5
1,2,3,alfa-romero stelvio,88.6,168.8,64.1,48.8,2548,130,3.47,...,16500.0,1,0,1,0,2,0,0,2,5
2,3,1,alfa-romero Quadrifoglio,94.5,171.2,65.5,52.4,2823,152,2.68,...,16500.0,1,0,1,2,2,0,5,3,5
3,4,2,audi 100 ls,99.8,176.6,66.2,54.3,2337,109,3.19,...,13950.0,1,0,0,3,1,0,3,2,5
4,5,2,audi 100ls,99.4,176.6,66.4,54.3,2824,136,3.19,...,17450.0,1,0,0,3,0,0,3,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),109.1,188.8,68.9,55.5,2952,141,3.78,...,16845.0,1,0,0,3,2,0,3,2,5
201,202,-1,volvo 144ea,109.1,188.8,68.8,55.5,3049,141,3.78,...,19045.0,1,1,0,3,2,0,3,2,5
202,203,-1,volvo 244dl,109.1,188.8,68.9,55.5,3012,173,3.58,...,21485.0,1,0,0,3,2,0,5,3,5
203,204,-1,volvo 246,109.1,188.8,68.9,55.5,3217,145,3.01,...,22470.0,0,1,0,3,2,0,3,3,3
204,205,-1,volvo 264gl,109.1,188.8,68.9,55.5,3062,141,3.78,...,22625.0,1,1,0,3,2,0,3,2,5

In [82]:
import numpy as np
cor_matrix = dataset_copy_new.corr().abs()
upper_tri = cor_matrix.where(np.triu(np.ones(cor_matrix.shape),k=1).astype(np.bool))
to_drop = [column for column in upper_tri.columns if any(upper_tri[column] > 0.9)]
dataset_copy_new1 = dataset_copy_new.drop(dataset_copy_new[to_drop], axis=1)
dataset_copy_new1

,car_ID,symboling,CarName,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,...,citympg,price,aspirationcopy,doornumbercopy,carbodycopy,drivewheelcopy,enginelocationcopy,enginetypecopy,cylindernumbercopy,fuelsystemcopy
0,1,3,alfa-romero giulia,88.6,168.8,64.1,48.8,2548,130,3.47,...,21,13495.0,0,1,0,2,0,0,2,5
1,2,3,alfa-romero stelvio,88.6,168.8,64.1,48.8,2548,130,3.47,...,21,16500.0,0,1,0,2,0,0,2,5
2,3,1,alfa-romero Quadrifoglio,94.5,171.2,65.5,52.4,2823,152,2.68,...,19,16500.0,0,1,2,2,0,5,3,5
3,4,2,audi 100 ls,99.8,176.6,66.2,54.3,2337,109,3.19,...,24,13950.0,0,0,3,1,0,3,2,5
4,5,2,audi 100ls,99.4,176.6,66.4,54.3,2824,136,3.19,...,18,17450.0,0,0,3,0,0,3,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),109.1,188.8,68.9,55.5,2952,141,3.78,...,23,16845.0,0,0,3,2,0,3,2,5
201,202,-1,volvo 144ea,109.1,188.8,68.8,55.5,3049,141,3.78,...,19,19045.0,1,0,3,2,0,3,2,5
202,203,-1,volvo 244dl,109.1,188.8,68.9,55.5,3012,173,3.58,...,18,21485.0,0,0,3,2,0,5,3,5
203,204,-1,volvo 246,109.1,188.8,68.9,55.5,3217,145,3.01,...,26,22470.0,1,0,3,2,0,3,3,3
204,205,-1,volvo 264gl,109.1,188.8,68.9,55.5,3062,141,3.78,...,19,22625.0,1,0,3,2,0,3,2,5

In [84]:
co = dataset_copy_new1.columns
dataset_copy_new1 = dataset_copy_new1.loc[:,['car_ID', 'CarName','symboling', 'wheelbase', 'carlength', 'carwidth',
       'carheight', 'curbweight', 'enginesize', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'price',
       'aspirationcopy', 'doornumbercopy', 'carbodycopy', 'drivewheelcopy',
       'enginelocationcopy', 'enginetypecopy', 'cylindernumbercopy',
       'fuelsystemcopy']]
dataset_copy_new1

,car_ID,CarName,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,...,citympg,price,aspirationcopy,doornumbercopy,carbodycopy,drivewheelcopy,enginelocationcopy,enginetypecopy,cylindernumbercopy,fuelsystemcopy
0,1,alfa-romero giulia,3,88.6,168.8,64.1,48.8,2548,130,3.47,...,21,13495.0,0,1,0,2,0,0,2,5
1,2,alfa-romero stelvio,3,88.6,168.8,64.1,48.8,2548,130,3.47,...,21,16500.0,0,1,0,2,0,0,2,5
2,3,alfa-romero Quadrifoglio,1,94.5,171.2,65.5,52.4,2823,152,2.68,...,19,16500.0,0,1,2,2,0,5,3,5
3,4,audi 100 ls,2,99.8,176.6,66.2,54.3,2337,109,3.19,...,24,13950.0,0,0,3,1,0,3,2,5
4,5,audi 100ls,2,99.4,176.6,66.4,54.3,2824,136,3.19,...,18,17450.0,0,0,3,0,0,3,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,volvo 145e (sw),-1,109.1,188.8,68.9,55.5,2952,141,3.78,...,23,16845.0,0,0,3,2,0,3,2,5
201,202,volvo 144ea,-1,109.1,188.8,68.8,55.5,3049,141,3.78,...,19,19045.0,1,0,3,2,0,3,2,5
202,203,volvo 244dl,-1,109.1,188.8,68.9,55.5,3012,173,3.58,...,18,21485.0,0,0,3,2,0,5,3,5
203,204,volvo 246,-1,109.1,188.8,68.9,55.5,3217,145,3.01,...,26,22470.0,1,0,3,2,0,3,3,3
204,205,volvo 264gl,-1,109.1,188.8,68.9,55.5,3062,141,3.78,...,19,22625.0,1,0,3,2,0,3,2,5

In [85]:
from sklearn.preprocessing import MinMaxScaler
data = dataset_copy_new1.iloc[:,2:].values
labels = dataset_copy_new1.iloc[:,:2].values
mm = MinMaxScaler()
data_normalized = mm.fit_transform(data)
new_data0 = pd.DataFrame(data_normalized ,columns=dataset_copy_new1.columns[2:])
new_data1 = pd.DataFrame(labels ,columns=dataset_copy_new1.columns[:2])
new_data = pd.concat([new_data1, new_data0], axis = 1)
new_data

,car_ID,CarName,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,...,citympg,price,aspirationcopy,doornumbercopy,carbodycopy,drivewheelcopy,enginelocationcopy,enginetypecopy,cylindernumbercopy,fuelsystemcopy
0,1,alfa-romero giulia,1.0,0.058309,0.413433,0.316667,0.083333,0.411171,0.260377,0.664286,...,0.222222,0.207959,0.0,1.0,0.00,1.0,0.0,0.000000,0.333333,0.714286
1,2,alfa-romero stelvio,1.0,0.058309,0.413433,0.316667,0.083333,0.411171,0.260377,0.664286,...,0.222222,0.282558,0.0,1.0,0.00,1.0,0.0,0.000000,0.333333,0.714286
2,3,alfa-romero Quadrifoglio,0.6,0.230321,0.449254,0.433333,0.383333,0.517843,0.343396,0.100000,...,0.166667,0.282558,0.0,1.0,0.50,1.0,0.0,0.833333,0.500000,0.714286
3,4,audi 100 ls,0.8,0.384840,0.529851,0.491667,0.541667,0.329325,0.181132,0.464286,...,0.305556,0.219254,0.0,0.0,0.75,0.5,0.0,0.500000,0.333333,0.714286
4,5,audi 100ls,0.8,0.373178,0.529851,0.508333,0.541667,0.518231,0.283019,0.464286,...,0.138889,0.306142,0.0,0.0,0.75,0.0,0.0,0.500000,0.166667,0.714286
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,volvo 145e (sw),0.2,0.655977,0.711940,0.716667,0.641667,0.567882,0.301887,0.885714,...,0.277778,0.291123,0.0,0.0,0.75,1.0,0.0,0.500000,0.333333,0.714286
201,202,volvo 144ea,0.2,0.655977,0.711940,0.708333,0.641667,0.605508,0.301887,0.885714,...,0.166667,0.345738,1.0,0.0,0.75,1.0,0.0,0.500000,0.333333,0.714286
202,203,volvo 244dl,0.2,0.655977,0.711940,0.716667,0.641667,0.591156,0.422642,0.742857,...,0.138889,0.406311,0.0,0.0,0.75,1.0,0.0,0.833333,0.500000,0.714286
203,204,volvo 246,0.2,0.655977,0.711940,0.716667,0.641667,0.670675,0.316981,0.335714,...,0.361111,0.430763,1.0,0.0,0.75,1.0,0.0,0.500000,0.500000,0.428571
204,205,volvo 264gl,0.2,0.655977,0.711940,0.716667,0.641667,0.610551,0.301887,0.885714,...,0.166667,0.434611,1.0,0.0,0.75,1.0,0.0,0.500000,0.333333,0.714286

In [94]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=5)
predict_y = kmeans.fit_predict(new_data.iloc[:,2:])
final_data = pd.DataFrame(predict_y,columns=['result'])
final_result = pd.concat([dataset_copy_new1, final_data], axis = 1)
final_result

,car_ID,CarName,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,...,price,aspirationcopy,doornumbercopy,carbodycopy,drivewheelcopy,enginelocationcopy,enginetypecopy,cylindernumbercopy,fuelsystemcopy,result
0,1,alfa-romero giulia,3,88.6,168.8,64.1,48.8,2548,130,3.47,...,13495.0,0,1,0,2,0,0,2,5,2
1,2,alfa-romero stelvio,3,88.6,168.8,64.1,48.8,2548,130,3.47,...,16500.0,0,1,0,2,0,0,2,5,2
2,3,alfa-romero Quadrifoglio,1,94.5,171.2,65.5,52.4,2823,152,2.68,...,16500.0,0,1,2,2,0,5,3,5,2
3,4,audi 100 ls,2,99.8,176.6,66.2,54.3,2337,109,3.19,...,13950.0,0,0,3,1,0,3,2,5,4
4,5,audi 100ls,2,99.4,176.6,66.4,54.3,2824,136,3.19,...,17450.0,0,0,3,0,0,3,1,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,volvo 145e (sw),-1,109.1,188.8,68.9,55.5,2952,141,3.78,...,16845.0,0,0,3,2,0,3,2,5,1
201,202,volvo 144ea,-1,109.1,188.8,68.8,55.5,3049,141,3.78,...,19045.0,1,0,3,2,0,3,2,5,3
202,203,volvo 244dl,-1,109.1,188.8,68.9,55.5,3012,173,3.58,...,21485.0,0,0,3,2,0,5,3,5,1
203,204,volvo 246,-1,109.1,188.8,68.9,55.5,3217,145,3.01,...,22470.0,1,0,3,2,0,3,3,3,3
204,205,volvo 264gl,-1,109.1,188.8,68.9,55.5,3062,141,3.78,...,22625.0,1,0,3,2,0,3,2,5,3

In [113]:
final_result.groupby("result")['CarName'].count()
final_result.loc[final_result["CarName"].str.contains('volkswagen'),:].groupby("result")['CarName'].count()

result
2    1
3    2
4    6
Name: CarName, dtype: int64

In [112]:
final_result.loc[final_result["CarName"].str.contains('volkswagen'),:].groupby("result")['CarName'].count()
# final_result.groupby("result").agg({"price":np.mean})
pd.DataFrame(final_result.groupby(["result","CarName"])['price'].mean())

                                      price
result CarName
0      audi 5000s (diesel)        17859.167
       dodge coronet custom        8558.000
       dodge coronet custom (sw)  12964.000
       dodge d200                  7957.000
       mercury cougar             16503.000
...                                     ...
4      volkswagen 411 (sw)         8495.000
       volkswagen dasher          11142.500
       volkswagen model 111        7995.000
       volkswagen rabbit          13295.000
       volkswagen type 3           8195.000

[171 rows x 1 columns]

In [114]:
# for i in range(0, 205):
#     temp = []
#     if 'volkswagen' in final_result.CarName[i]:
#         for j in range(0, 205):
#             if final_result.result[j] == final_result.result[i] and 'volkswagen' not in final_result.CarName[j] :
#                 temp.append(final_result.CarName[j])
#         print('-------------------------------------')
#         print(f'{final_result.CarName[i]}:{temp}')

In [127]:
a = final_result[final_result['result'] == 4].loc[:,['CarName','price','result']]
# np.max(final_result[final_result['result'] == 4].loc[:,['price']])
a

                 CarName    price  result
3            audi 100 ls  13950.0       4
4             audi 100ls  17450.0       4
20   chevrolet vega 2300   6575.0       4
24     dodge monaco (sw)   6229.0       4
25    dodge colt hardtop   6692.0       4
..                   ...      ...     ...
185    volkswagen type 3   8195.0       4
186  volkswagen 411 (sw)   8495.0       4
188    volkswagen dasher   9995.0       4
191    volkswagen rabbit  13295.0       4
193    volkswagen dasher  12290.0       4

[65 rows x 3 columns]

In [129]:
# a.groupby(pd.cut(a["price"], np.arange(6229, 18345, 2000))).mean()